/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ozvekqvczxpzcmxwuysj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dmVrcXZjenhwemNteHd1eXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDUzOTEsImV4cCI6MjA3MDA4MTM5MX0.y-VD3W-E3KfYzC2_Bs0ozZfNn5qKHEffT7AR31PKzDk"